sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pjWYhHnL2DF4rEx3WgLUfgCoRVYu+BG8QKunlO9d2Vb6S0lXQSYaBhcM/gdQ/5L8WirU7eU+X+cSmyjGGgmd63AKXcKUmLwGJWt3WGVukQnmA5XBcyQHjcKJGV3ZHX/X+K8Ou2G9m5G8NvXavD4LVZNNVkKDgah2pLHNNQFLKT7smHyCk7VezUKt/Xq7D72TLIO508QRpK/SD13btBhySolF8LSVZ0+5dZfP1UP0RBCbhICULCpOUt7X2zENQaweL/jZpuPZHeWVYDcPhwy8lYS2phmj2C9U+Lg8rdTxo7weHzv9I5hpLgexec74e/JTYUl8ZbQdVCdRI/QyiQR+oiAgIcwesCmUJ4VZ8FGheq8YivaOdWyozyoznIpjBTu6LvV4HFVRvBdzojH8LXtQJW7DO3jeiviNr0NhvpPrmWWtKmoh6qDCV9SGw1u2ExbP0M4T4rMQZ1TSgzi/952a3ggR/ZAUOAgMokwOPpL0mUeMFlyC7VKraxETRnxKDmY50akx1QeGJGe6pbwmdvJBapD4gd/BDQ3vkf5bpaFaz18agIj9F7rOBa3JOK7wrKD6iXWAWQ/pwhKEVdWeGyNV3MTnuG15ZM9etdNt9+A79n+Tluc7FMg+mbLWsCDQRPcp7zXMyYPuf3+smPuvSD5I1pn2X9lDQG7OENEqW+qvqUQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Complete-Original-Short-Stories-of-Guy-De-Maupassant_3090
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy